### ISSUE TITLE
no external crate `stm32f103`

### ISSUE THREAD

**Issue by adminSxs** [rtic-rs/cortex-m-rtic#656]
```toml
[dependencies.stm32f1xx-hal]
version = "0.9.0"
features = ["rt", "stm32f103","medium"]
```

```rust
#[rtic::app(device = stm32f103)]
mod app {
...

}
```
#[rtic::app(device = stm32f1xx_hal)]
#[rtic::app(device = stm32f1)]
#[rtic::app(device = stm32f103)]

compile error: `no external crate `stm32fxxxxx``
